document.addEventListener("DOMContentLoaded", () => {
  const VALID_DURATION = 24 * 60 * 60 * 1000; // 24 hours
  const now = Date.now();

  const urlParams = new URLSearchParams(window.location.search);
  const currentId = urlParams.get("id");
  const hasId = currentId !== null;

  const fullPath = window.location.pathname + (hasId ? `?id=${currentId}` : "");

  const storedData = JSON.parse(localStorage.getItem("validDynamicURLInfo"));

  // CASE 1: There is a stored valid ID
  if (storedData) {
    const isSameURL = storedData.url === fullPath;
    const notExpired = now - storedData.timestamp <= VALID_DURATION;

    if (isSameURL && notExpired) {
      // ✅ Match and still valid
      const output = document.getElementById("output");
      if (output) {
        output.innerHTML = `<p>This URL is valid for 24 hours: <strong>${fullPath}</strong></p>`;
      }
      return;
    } else {
      // ❌ Tampered ID or expired
      document.body.innerHTML = "<h2>This URL is invalid or has expired.</h2>";
      return;
    }
  }

  // CASE 2: No stored ID yet, and no ?id in URL → generate new
  if (!hasId) {
    const newId = Math.floor(Math.random() * 100000);
    const newURL = `${window.location.pathname}?id=${newId}`;

    localStorage.setItem(
      "validDynamicURLInfo",
      JSON.stringify({
        url: newURL,
        timestamp: now
      })
    );

    // Set new URL without reloading
    window.history.replaceState({}, "", newURL);

    const output = document.getElementById("output");
    if (output) {
      output.innerHTML = `<p>New URL generated and valid for 24 hours: <strong>${newURL}</strong></p>`;
    }
    return;
  }

  // ❌ CASE 3: ID is present but was never generated/stored
  document.body.innerHTML = "<h2>This URL was not generated by this browser and is not valid.</h2>";
});
